name: shop_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  dartz: ^0.10.1
  get_it: ^7.6.4
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_credit_card: ^4.0.1
  image_picker: ^1.0.7
  flutter_phoenix: ^1.1.1





dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_logo.png"


  flutter_lints: ^3.0.1



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  assets:
     - assets/image/
     - assets/font/
     - assets/json/





  fonts:
     - family: Poppins
       fonts:
         - asset: assets/font/Poppins-Bold.ttf
           weight: 700
         - asset: assets/font/Poppins-Regular.ttf
           weight: 400
         - asset: assets/font/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/font/Poppins-Medium.ttf
           weight: 500


     - family: IconBroken
       fonts:
         - asset: assets/font/icons.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
